### PR TITLE
Improve build system

### PR DESCRIPTION
**Pull request by Fantu**
I have near no experience with cmake, I read some documentation and examples and I tried to do an initial standard build as part of https://github.com/veeam/blksnap/issues/38
I had some difficult, library and tools part build is working (for now tested with circleci on debian10-11-12,ubuntu20.04,22.04,22.10) but not optimal.
Any advice for improvements is appreciated.

TODO:
The tests part is incomplete, readme need to be updated

UPDATE 26/12: tests part completed

UPDATE 27:12: updated README and added uninstall target

### CODE REVIEW

**Comment by Fantu** [comment]
@SergeiShtepa after had initial "standard build system" I made also the debian packages more standard and including all hardening (https://wiki.debian.org/Hardening) the build failed with errors:

```
[ 57%] Building CXX object lib/blksnap/CMakeFiles/blksnap-dev.dir/Session.cpp.o
cd /home/fabio/repository/blksnap/obj-x86_64-linux-gnu/lib/blksnap && /usr/bin/c++   -I/home/fabio/repository/blksnap/../../include  -g -O2 -fdebug-prefix-map=/home/fabio/repository/blksnap=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -Wdate-time -D_FORTIFY_SOURCE=2 -static-libstdc++ -static-libgcc -pthread -O2 -g -DNDEBUG   -std=gnu++14 -o CMakeFiles/blksnap-dev.dir/Session.cpp.o -c /home/fabio/repository/blksnap/lib/blksnap/Session.cpp
In file included from /usr/include/fcntl.h:301,
                 from /home/fabio/repository/blksnap/lib/blksnap/Session.cpp:24:
In function ‘int open(const char*, int, ...)’,
    inlined from ‘void {anonymous}::FallocateStorage(const string&, off_t)’ at /home/fabio/repository/blksnap/lib/blksnap/Session.cpp:207:24:
/usr/include/x86_64-linux-gnu/bits/fcntl2.h:50:24: error: call to ‘__open_missing_mode’ declared with attribute error: open with O_CREAT or O_TMPFILE in second argument needs 3 arguments
   50 |    __open_missing_mode ();
      |    ~~~~~~~~~~~~~~~~~~~~^~
```

```
[ 85%] Building CXX object tools/blksnap/CMakeFiles/blksnap-tools.dir/main.cpp.o
cd /home/fabio/repository/blksnap/obj-x86_64-linux-gnu/tools/blksnap && /usr/bin/c++  -DBLK_SNAP_MODIFICATION -DBOOST_ALL_NO_LIB -I/home/fabio/repository/blksnap/tools/blksnap/. -I/home/fabio/repository/blksnap/../../include  -g -O2 -fdebug-prefix-map=/home/fabio/repository/blksnap=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -Wdate-time -D_FORTIFY_SOURCE=2 -static-libstdc++ -static-libgcc -O2 -g -DNDEBUG   -std=gnu++14 -o CMakeFiles/blksnap-tools.dir/main.cpp.o -c /home/fabio/repository/blksnap/tools/blksnap/main.cpp
/home/fabio/repository/blksnap/tools/blksnap/main.cpp:247:17: note: #pragma message: BLK_SNAP_MODIFICATION defined
  247 | #pragma message "BLK_SNAP_MODIFICATION defined"
      |                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /usr/include/fcntl.h:301,
                 from /home/fabio/repository/blksnap/tools/blksnap/main.cpp:6:
In function ‘int open(const char*, int, ...)’,
    inlined from ‘void StretchSnapshotArgsProc::ProcessLowFreeSpace(const {anonymous}::CBlksnapFileWrap&, unsigned int, blk_snap_event_low_free_space*)’ at /home/fabio/repository/blksnap/tools/blksnap/main.cpp:803:20,
    inlined from ‘virtual void StretchSnapshotArgsProc::Execute(boost::program_options::variables_map&)’ at /home/fabio/repository/blksnap/tools/blksnap/main.cpp:891:40:
/usr/include/x86_64-linux-gnu/bits/fcntl2.h:50:24: error: call to ‘__open_missing_mode’ declared with attribute error: open with O_CREAT or O_TMPFILE in second argument needs 3 arguments
   50 |    __open_missing_mode ();
      |    ~~~~~~~~~~~~~~~~~~~~^~
```

I fixed the build with session.cpp and main.cpp changes in this PR but I'm not sure I set the correct file permissions

**Comment by SergeiShtepa** [comment]
Thanks. 
'll look closely later.
At first glance, there are no problems in the code.

**Comment by Fantu** [comment]
thanks for the answer, this evening if I have time I'll relook it and I'll also update the readme
I also spotted a thing I think is not good (even if working on linux on major of filesystem): in include/blksnap/ Blksnap.h and blksnap.h. I think is better have 2 different name and not just capitalizing on a letter

**Comment by Fantu** [comment]
Updated also README and added uninstall target (not autogenerated by cmake)

On circleci tests cmake uninstall file was not found even if I not
understand why, manually both with only "cmake ." and also generating debian
packages (same of circleci tests) is ok.
I did some try without find a solution so I added an exists check for
don't fail in similar cases

Make install and uninstall print wrong text related to some tests files don't
installed or uninstalled as not found but checking them was installed
and uninstalled correctly, also for this I didn't found a solution but seems only a minor thing of printed text

**Pull request merged**
