### PR TITLE
Small improve to README files

### PR DESCRIPTION
**Pull request by Fantu**

### CODE REVIEW

**Comment by Fantu** [comment]
@SergeiShtepa log don't contain blksnap output even if I use
`sudo ./all.sh 2>&1 | tee -a /tmp/blksnap_test_$(date -u '+%Y-%m-%d_%H-%M-%S').log`
that should redirect stderr so log should contain all stdout and stderr but blksnap command output (like errors) are only showed in terminal
I missed something or is there something in blksnap tool? like also the issue that there are issues in tests for command still running when continue to execute the script

**Comment by SergeiShtepa** [comment]
> `sudo ./all.sh 2>&1 | tee -a /tmp/blksnap_test_$(date -u '+%Y-%m-%d_%H-%M-%S').log`

Maybe `sudo ./all.sh 2>&1 >/tmp/blksnap_test_$(date -u '+%Y-%m-%d_%H-%M-%S').log` will work?
Still possible in the script blksnap.sh when calling blksnap, do redirection 2>&1.

> like also the issue that there are issues in tests for command still running when continue to execute the script

As usual, there is often not enough time to develop tests. :)
It probably makes sense to create an "issue" to fix problems in tests.

**Comment by Fantu** [comment]
@SergeiShtepa as already tried can be used because don't show the output and some "press" is needed actually
and anyway there is some output not included in log but only show on terminal, like my latest test now:
```
64+0 record dentro
64+0 record fuori
67108864 bytes (67 MB, 64 MiB) copied, 0,0430367 s, 1,6 GB/s
mke2fs 1.45.5 (07-Jan-2020)
128+0 record dentro
128+0 record fuori
134217728 bytes (134 MB, 128 MiB) copied, 0,0891908 s, 1,5 GB/s
mke2fs 1.45.5 (07-Jan-2020)

4096+0 record dentro
4096+0 record fuori
4294967296 bytes (4,3 GB, 4,0 GiB) copied, 9,0013 s, 477 MB/s
mke2fs 1.45.5 (07-Jan-2020)



[TBD]Failed to get event from snapshot.: No such process
Stretch snapshot service failed.
4096+0 record dentro
4096+0 record fuori
4294967296 bytes (4,3 GB, 4,0 GiB) copied, 9,01493 s, 476 MB/s
mke2fs 1.45.5 (07-Jan-2020)
[TBD]Failed to get event from snapshot.: No such process
Stretch snapshot service failed.
zramctl: /dev/zram0: failed to reset: Dispositivo o risorsa occupata
```
like the tests I did yesterday with latest upstream patch build (now updating the module instead) seems there is also a regression, probably I suppose probably can be related to something already spotted in the review of Christoph Hellwig

If you need full log I'll execute without log and I'll copy to file the full output for see in "correct order" (except probably for cases already reported in https://github.com/veeam/blksnap/issues/34)

**Comment by SergeiShtepa** [comment]
Great.

> probably I suppose probably can be related to something already spotted in the review of Christoph Hellwig

No. It's just that the tests need improvement.

**Pull request merged**
