### PR TITLE
Add licensing part to README and make working github license autodetect

### PR DESCRIPTION
**Pull request by Fantu**

### CODE REVIEW

**Comment by SergeiShtepa** [comment]
Sorry, I can't change the license file.
It was in this form that it was agreed with the legal department.

**Comment by Fantu** [comment]
@SergeiShtepa is not license change, I wrote what is set actually looking also source files
Kernel module is GPL-2 only, tools and tests are GPL-2+, library and include are LGPL-3+.
what is wrong?
I saw use of deprecate spdx tag like GPL-2.0 (instead of GPL-2.0-only), and GPL-2.0+ (instead of GPL-2.0+) but I suppose that was poiting to right licenses

**Comment by Fantu** [comment]
added also the copyright line to the README

**Comment by SergeiShtepa** [comment]
Thanks.
I wrote to our lawyers.
The approval may take some time.

**Comment by Fantu** [comment]
@SergeiShtepa I not understand, the headers in source files was with a "wrong" license? I only write in readme a small description of licenses actually used based
and for make github autodetect the license and list them right I simply removed the first lines in LICENSE.md related to SPDX use (there is explain in CONTRIBUTING now, can be improved if needed) so detect correctly the GPL-2.0 and added the LGPL-3.0 full text as LICENSE.LIB so detect and list correctly also that used in the library part
now without don't show license or show "other" with the risk that users think there is a proprietary license and avoid it, instead if they are detected correctly by github they are showned below the repository description in searches.
and also it seems good to me to have a short and clear description of the licenses used in the README

**Comment by SergeiShtepa** [comment]
Thank you, Fabio.
I am sure that everything is right and correct.
But I am obliged to coordinate any licensing issues with lawyers. Even if it 's just a punctuation correction .

**Comment by Fantu** [comment]
@SergeiShtepa One think strange I saw is where was changed to spdx was removed the copyright line, probably an improvements can be migrate all files to spdx (for now not all are using it), replace the deprecated license tag and add also copyright line when missed, should be for example:
`SPDX-FileCopyrightText: 2022 Veeam Software Group GmbH`
(see https://reuse.software/faq/)

**Comment by SergeiShtepa** [comment]
> The approval may take some time.

I discussed it with our lawyer . The changes are accepted.

> probably an improvements can be migrate all files to spdx (for now not all are using it), replace the deprecated license tag and add also copyright line when missed, should be for example:
SPDX-FileCopyrightText: 2022 Veeam Software Group GmbH

There may be an inaccuracy here.

**Comment by Fantu** [comment]
@SergeiShtepa what is the inaccuracy you mean?

**Pull request merged**
